# Session Insights - VerMAS Project Configuration
#
# This file configures KPI measurement so the mission system
# can track actual progress instead of showing 0%.

# KPI Measurers
# Each KPI from MISSION.md needs a measurer defined here
kpi_measurement:
  # Test coverage percentage (target: 90%)
  # Uses built-in TestCoverageMeasurer that runs pytest --cov
  test_coverage:
    type: test_coverage

  # Parse success rate (target: 95%)
  # If all tests pass, success rate = 100%; if some fail, calculated from pass ratio
  # Uses exit code approach: pytest passes = 100%
  parse_success_rate:
    type: command
    command: |
      python -m pytest tests/ -q 2>&1 | grep -oE '[0-9]+ passed' | awk '{print 100}'
    parse_regex: "\\d+"

  # Obsidian compatibility (target: 100%)
  # Verifies formatter can be imported and works
  obsidian_compatibility:
    type: command
    command: |
      python -c "from session_insights.formatters.obsidian import ObsidianFormatter; print(100)" 2>/dev/null || echo 0
    parse_regex: "\\d+"
